name: langchain_env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch # for torch
  - numpy
  - scipy
  - scikit-learn
  - transformers
  - pip
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - fastapi==0.121.3
      - filelock==3.19.1
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib_metadata==8.7.0
      - Jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-core==0.3.80
      - langchain-huggingface==0.3.1
      - langchain-ollama==0.3.10
      - langchain-openai==0.3.35
      - langsmith==0.4.37
      - MarkupSafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - ollama==0.6.1
      - openai==2.8.1
      - orjson==3.11.4
      - packaging==25.0
      - pillow==11.3.0
      - protobuf
      - pydantic==2.12.4
      - pydantic_core==2.41.5
      - python-dotenv==1.2.1
      - PyYAML==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - safetensors==0.7.0
      - sentence-transformers
      - sentencepiece
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.49.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - typing_extensions==4.15.0
      - urllib3==2.5.0
      - uv==0.9.11
      - uvicorn==0.38.0
      - zipp==3.23.0
      - zstandard==0.25.0
      - sqlalchemy==2.0.35
      - psycopg2-binary==2.9.9
      - alembic==1.13.1
